### ISSUE TITLE
Consider allowing 'ref' allele as qualifier on VA statements

### ISSUE THREAD

**Issue by mbrush** [ga4gh-gks/variant-annotation-model#44]
We should consider whether we want to capture as part of VA statements the nature of the 'ref' state when the subject allele is considered 'alt'.  This originally came up in the context of Population Frequency annotations, so I will draw examples from this VA type, but it is a consideration for all VA types.

This is of course not relevant in cases where there is no indication of the ref vs alt status of the subject allele -  e.g. for Ensembl PopFreq annotations such as [these](http://jsonviewer.stack.hu/#http://rest.ensembl.org/variation/human/rs34637584?content-type=application/json;pops=1;genotypes=1). But most data sources such as CellBase and gnomAD/ExAC indicate the ref->alt change when they annotate an alt allele - either in the HGVS label they give the allele (e.g. [here),](https://gnomad.broadinstitute.org/variant/12-40734202-G-A?dataset=gnomad_r2_1) or as part of the structured data itself (e.g. [here](http://bioinfo.hpc.cam.ac.uk/cellbase/webservices/rest/v4/hsapiens/genomic/variant/19:45411941:T:C/annotation?include=populationFrequencies)).

For good reason, we had previously decided on VR and VA calls that ref vs alt status of an allele should not be captured as part of the foundational variant representation itself. But in the context of an annotation, this status may be important information to convey, and if a source explicitly captures this info we should consider if/how we might do the same.  A simple approach would be to allow for an optional 'referenceAlleleQualifier' attribute on the PopFreq statement, to capture the nature of the 'ref' state when the subject allele is considered 'alt'. e.g. for the CellBase example above:

````
subject: vmc:GA_xXBYkzzu1AH0HRbLeFESvllmAKUNN1MF (NC_000019.9 45411941 C)
predicate: is_described_by
descriptor:  
   - id: va:StudyData001
     variationFrequency: 0.20852435
     homozygousIndividualFrequency: 0.04497584
     heterozygousIndividualFrequency: 0.32709703 
populationQualifier: va:Population001 
refAlleleQualifier:  "T"
````
The implication here is that "T" is the reference state for the subject "C" allele, on the NC_000019.9 reference used to define it.
